"""
UserLesson model — persists AI-generated personalized lessons per user.

Unlike the static Lesson table (seeded curriculum), UserLesson records are
dynamically generated by the AI coaching engine, stored per user, and track
completion state.
"""

import uuid
from datetime import datetime
from sqlalchemy import (
    String, Text, Boolean, Float, DateTime, Integer,
    ForeignKey, func
)
from sqlalchemy.orm import Mapped, mapped_column
from app.database import Base


class UserLesson(Base):
    __tablename__ = "user_lessons"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True
    )
    session_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("sessions.id", ondelete="SET NULL"), nullable=True,
        comment="The simulation session this lesson was generated from"
    )
    generated_reason: Mapped[str | None] = mapped_column(
        String(500), nullable=True,
        comment="Specific reason this lesson was generated from the session"
    )
    recommended_focus: Mapped[str | None] = mapped_column(
        String(300), nullable=True,
        comment="What the user should focus on during their next session"
    )

    # ── Content fields (AI-generated) ────────────────────────────────────────
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    lesson_category: Mapped[str] = mapped_column(
        String(100), nullable=False, default="Defensive Decision",
        comment="Cognitive Control | Attention Regulation | Emotional Regulation | Defensive Decision | Recovery & Adaptation"
    )
    behavioral_diagnosis: Mapped[str] = mapped_column(
        Text, nullable=False, default="",
        comment="Explain detected weakness"
    )
    psychological_interpretation: Mapped[str] = mapped_column(
        Text, nullable=False, default="",
        comment="Why the behavior occurred cognitively/emotionally"
    )
    real_world_risk_impact: Mapped[str] = mapped_column(
        Text, nullable=False, default="",
        comment="How this affects real driving behavior"
    )
    cognitive_coaching_narrative: Mapped[str] = mapped_column(
        Text, nullable=False, default="",
        comment="Human-like adaptive coaching, replacing ai_coaching_advice"
    )
    scenario_replay_analysis: Mapped[str] = mapped_column(
        Text, nullable=False, default="",
        comment="Break down important simulation moments"
    )
    behavioral_exercises: Mapped[str] = mapped_column(
        Text, nullable=False, default="[]",
        comment="JSON array of interactive improvement drills"
    )
    mental_conditioning_techniques: Mapped[str] = mapped_column(
        Text, nullable=False, default="[]",
        comment="JSON array of techniques like delayed-response conditioning"
    )
    attention_reinforcement_tasks: Mapped[str] = mapped_column(
        Text, nullable=False, default="[]",
        comment="JSON array of practical training suggestions"
    )
    future_risk_projection: Mapped[str] = mapped_column(
        Text, nullable=False, default="",
        comment="What happens if behavior continues"
    )
    personalized_improvement_strategy: Mapped[str] = mapped_column(
        Text, nullable=False, default="",
        comment="Adaptive intervention roadmap"
    )

    # ── Metrics ───────────────────────────────────────────────────────────────
    difficulty: Mapped[str] = mapped_column(
        String(20), nullable=False, default="Intermediate",
        comment="Beginner | Intermediate | Advanced"
    )
    driver_type: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Driver profile type when this lesson was generated"
    )
    reaction_time_target: Mapped[float] = mapped_column(
        Float, nullable=False, default=2.5,
        comment="Target avg reaction time in seconds"
    )
    distraction_tolerance_target: Mapped[float] = mapped_column(
        Float, nullable=False, default=0.85,
        comment="Target safe decision ratio 0.0-1.0"
    )
    ai_provider: Mapped[str] = mapped_column(
        String(50), nullable=False, default="fallback",
        comment="Which LLM provider generated this lesson"
    )

    # ── Completion Tracking ───────────────────────────────────────────────────
    completed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    review_count: Mapped[int] = mapped_column(
        nullable=False, default=0, server_default="0",
        comment="Number of times this lesson was reviewed/retaken"
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    def __repr__(self) -> str:
        return f"<UserLesson user={self.user_id} title={self.title[:40]} completed={self.completed}>"
