"""
UserLesson model — persists AI-generated personalized lessons per user.

Unlike the static Lesson table (seeded curriculum), UserLesson records are
dynamically generated by the AI coaching engine, stored per user, and track
completion state.
"""

import uuid
from datetime import datetime
from sqlalchemy import (
    String, Text, Boolean, Float, DateTime,
    ForeignKey, func
)
from sqlalchemy.orm import Mapped, mapped_column
from app.database import Base


class UserLesson(Base):
    __tablename__ = "user_lessons"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True
    )

    # ── Content fields (AI-generated) ────────────────────────────────────────
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    behavioral_target: Mapped[str] = mapped_column(
        String(300), nullable=False,
        comment="The specific behavioral weakness this lesson addresses"
    )
    why_it_matters: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="Psychological + safety explanation"
    )
    ai_coaching_advice: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="2-4 sentence adaptive coaching generated by LLM"
    )
    exercises: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="JSON array of recommended exercise strings"
    )
    personalized_insight: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="Personalized insight based on user's specific data"
    )
    improvement_goal: Mapped[str] = mapped_column(
        String(300), nullable=False,
        comment="Estimated improvement target, e.g. 'Reduce unsafe reactions by 15% in 5 sessions'"
    )
    simulation_modes: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="JSON array of recommended simulation modes"
    )

    # ── Metrics ───────────────────────────────────────────────────────────────
    difficulty: Mapped[str] = mapped_column(
        String(20), nullable=False, default="Intermediate",
        comment="Beginner | Intermediate | Advanced"
    )
    driver_type: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Driver profile type when this lesson was generated"
    )
    reaction_time_target: Mapped[float] = mapped_column(
        Float, nullable=False, default=2.5,
        comment="Target avg reaction time in seconds"
    )
    distraction_tolerance_target: Mapped[float] = mapped_column(
        Float, nullable=False, default=0.85,
        comment="Target safe decision ratio 0.0-1.0"
    )
    ai_provider: Mapped[str] = mapped_column(
        String(50), nullable=False, default="fallback",
        comment="Which LLM provider generated this lesson"
    )

    # ── Completion Tracking ───────────────────────────────────────────────────
    completed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    completion_score: Mapped[float] = mapped_column(
        Float, nullable=True,
        comment="Score achieved when completing the lesson (0-100)"
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    def __repr__(self) -> str:
        return f"<UserLesson user={self.user_id} title={self.title[:40]} completed={self.completed}>"
