"""add_cognitive_report

Revision ID: 1de207e2f5ee
Revises: 985b8b4673f1
Create Date: 2026-05-20 10:35:04.841729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de207e2f5ee'
down_revision: Union[str, None] = '985b8b4673f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cognitive_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=False, comment='High-level behavioral interpretation paragraph'),
    sa.Column('cognitive_analysis', sa.Text(), nullable=False, comment='How the driver thinks under pressure — mechanistic interpretation'),
    sa.Column('emotional_trigger_breakdown', sa.Text(), nullable=False, comment='JSON: {trigger_type, susceptibility_pct, explanation}[]'),
    sa.Column('behavioral_timeline', sa.Text(), nullable=False, comment='JSON: [{event_num, scenario_type, decision, reaction_time, cognitive_state, interpretation}]'),
    sa.Column('attention_stability_analysis', sa.Text(), nullable=False, comment='Focus degradation pattern narrative + structured metrics'),
    sa.Column('risk_projection', sa.Text(), nullable=False, comment='Future behavioral risk prediction paragraph'),
    sa.Column('consistency_analysis', sa.Text(), nullable=False, comment='Self-reported profile vs actual simulation behavior comparison'),
    sa.Column('intervention_strategy', sa.Text(), nullable=False, comment='JSON: [{technique, rationale, priority}] — personalized intervention plan'),
    sa.Column('coaching_narrative', sa.Text(), nullable=False, comment='Human-like psychological coaching voice — 3-4 paragraphs'),
    sa.Column('recommended_simulations', sa.Text(), nullable=False, comment='JSON: [{type, difficulty, rationale, targets_weakness}]'),
    sa.Column('urgency_susceptibility_index', sa.Float(), nullable=False, comment='0.0–1.0: how strongly urgency cues drove unsafe decisions'),
    sa.Column('authority_pressure_sensitivity', sa.Float(), nullable=False, comment='0.0–1.0: compliance rate under authority-framed pressure'),
    sa.Column('cognitive_overload_score', sa.Float(), nullable=False, comment='0.0–1.0: failure rate under compound distraction load'),
    sa.Column('emotional_reactivity_index', sa.Float(), nullable=False, comment='0.0–1.0: emotional decision influence rate'),
    sa.Column('defensive_attention_stability', sa.Float(), nullable=False, comment='0.0–1.0: sustained attention without degradation'),
    sa.Column('reassurance_seeking_probability', sa.Float(), nullable=False, comment='0.0–1.0: tendency to check after ignoring a distraction'),
    sa.Column('session_score', sa.Float(), nullable=False),
    sa.Column('safe_decision_rate', sa.Float(), nullable=False),
    sa.Column('total_events_in_session', sa.Integer(), nullable=False),
    sa.Column('driver_profile_at_time', sa.String(length=50), nullable=False),
    sa.Column('personality_label_at_time', sa.String(length=50), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=False),
    sa.Column('generation_stage', sa.String(length=20), nullable=False, comment='complete | partial | fallback'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cognitive_reports_session_id'), 'cognitive_reports', ['session_id'], unique=False)
    op.create_index(op.f('ix_cognitive_reports_user_id'), 'cognitive_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cognitive_reports_user_id'), table_name='cognitive_reports')
    op.drop_index(op.f('ix_cognitive_reports_session_id'), table_name='cognitive_reports')
    op.drop_table('cognitive_reports')
    # ### end Alembic commands ###
