"""add evolution fields

Revision ID: 654618078c49
Revises: de2b53b078d3
Create Date: 2026-06-09 08:38:15.073198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654618078c49'
down_revision: Union[str, None] = 'de2b53b078d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progressions', sa.Column('class_tier', sa.Integer(), server_default='1', nullable=False))
    op.add_column('user_progressions', sa.Column('class_xp_progress', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_progressions', sa.Column('class_evolution_at', sa.Integer(), server_default='2500', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progressions', 'class_evolution_at')
    op.drop_column('user_progressions', 'class_xp_progress')
    op.drop_column('user_progressions', 'class_tier')
    # ### end Alembic commands ###
