"""replace completion_score with review_count

Revision ID: 6a8d1bce503f
Revises: acb98383fae0
Create Date: 2026-05-28 04:45:59.408537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8d1bce503f'
down_revision: Union[str, None] = 'acb98383fae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lessons', sa.Column('review_count', sa.Integer(), nullable=False, server_default='0', comment='Number of times this lesson was reviewed/retaken'))
    op.drop_column('user_lessons', 'completion_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lessons', sa.Column('completion_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Score achieved when completing the lesson (0-100)'))
    op.drop_column('user_lessons', 'review_count')
    # ### end Alembic commands ###
