"""add_missions_and_boss_challenges

Revision ID: 80eb107e363f
Revises: 654618078c49
Create Date: 2026-06-10 14:27:33.446440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80eb107e363f'
down_revision: Union[str, None] = '654618078c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_missions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mission_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mission_type', sa.Enum('complete_sessions', 'achieve_score', 'ignore_distractions', 'react_fast', 'use_voice', name='missiontype'), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_date', 'slot', name='uq_mission_date_slot')
    )
    op.create_index(op.f('ix_daily_missions_mission_date'), 'daily_missions', ['mission_date'], unique=False)
    op.create_table('weekly_boss_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_score', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('badge_key', sa.String(length=60), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_boss_challenges_week_start'), 'weekly_boss_challenges', ['week_start'], unique=True)
    op.create_table('user_boss_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('boss_id', sa.String(length=36), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=False),
    sa.Column('beaten', sa.Boolean(), nullable=False),
    sa.Column('xp_awarded', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['weekly_boss_challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'boss_id', name='uq_user_boss')
    )
    op.create_index(op.f('ix_user_boss_attempts_user_id'), 'user_boss_attempts', ['user_id'], unique=False)
    op.create_table('user_mission_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('xp_awarded', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['daily_missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mission_id', name='uq_user_mission')
    )
    op.create_index(op.f('ix_user_mission_progress_user_id'), 'user_mission_progress', ['user_id'], unique=False)
    op.add_column('user_progressions', sa.Column('streak_freeze_tokens', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progressions', 'streak_freeze_tokens')
    op.drop_index(op.f('ix_user_mission_progress_user_id'), table_name='user_mission_progress')
    op.drop_table('user_mission_progress')
    op.drop_index(op.f('ix_user_boss_attempts_user_id'), table_name='user_boss_attempts')
    op.drop_table('user_boss_attempts')
    op.drop_index(op.f('ix_weekly_boss_challenges_week_start'), table_name='weekly_boss_challenges')
    op.drop_table('weekly_boss_challenges')
    op.drop_index(op.f('ix_daily_missions_mission_date'), table_name='daily_missions')
    op.drop_table('daily_missions')
    # ### end Alembic commands ###
