"""add_personality_profiles_and_scenarios

Revision ID: 985b8b4673f1
Revises: f3b36928a611
Create Date: 2026-05-20 10:06:51.064419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985b8b4673f1'
down_revision: Union[str, None] = 'f3b36928a611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
