"""initial_squashed_schema

Revision ID: 99f7577be3a1
Revises: 
Create Date: 2026-06-02 10:37:52.976619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f7577be3a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_platform_insights_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('insights_text', sa.Text(), nullable=False),
    sa.Column('analyzed_users_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_sessions_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_feedback_insights_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('insights_text', sa.Text(), nullable=False),
    sa.Column('analyzed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavioral_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('safe_decisions', sa.Integer(), nullable=False),
    sa.Column('unsafe_decisions', sa.Integer(), nullable=False),
    sa.Column('impulsive_count', sa.Integer(), nullable=False),
    sa.Column('hesitant_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_mistakes', sa.Integer(), nullable=False),
    sa.Column('pressure_level', sa.Integer(), nullable=False),
    sa.Column('avg_reaction_time', sa.Float(), nullable=False),
    sa.Column('fastest_reaction', sa.Float(), nullable=False),
    sa.Column('slowest_reaction', sa.Float(), nullable=False),
    sa.Column('fail_scenario_counts', sa.String(length=512), nullable=False),
    sa.Column('dominant_fail_scenario', sa.String(length=64), nullable=False),
    sa.Column('pressure_yield_count', sa.Integer(), nullable=False),
    sa.Column('pressure_resist_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_states_user_id'), 'behavioral_states', ['user_id'], unique=True)
    op.create_table('calibration_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Foreign key to users.id — not enforced at DB level for resilience'),
    sa.Column('scenario_id', sa.String(length=16), nullable=False, comment='e.g. S1, S2, S3, S4, S5, S6'),
    sa.Column('scenario_name', sa.String(length=64), nullable=False, comment='Human label: navigation_interrupt, countdown_clock, etc.'),
    sa.Column('first_response_ms', sa.Integer(), nullable=False, comment='Time in ms from scenario start to first user interaction'),
    sa.Column('time_to_choice_ms', sa.Integer(), nullable=False, comment='Time in ms from scenario start to final choice commitment'),
    sa.Column('interaction_count', sa.Integer(), nullable=False, comment='Total number of interaction events (clicks/taps) during scenario'),
    sa.Column('distraction_clicks', sa.Integer(), nullable=False, comment='Clicks on non-primary/distraction elements'),
    sa.Column('re_read_count', sa.Integer(), nullable=False, comment='Number of times user hovered/focused on option text before choosing'),
    sa.Column('choice_made', sa.String(length=32), nullable=False, comment='Identifier of the final option selected'),
    sa.Column('abandoned', sa.Boolean(), nullable=False, comment='True if scenario timed out without a choice'),
    sa.Column('evidence_impulsiveness', sa.Float(), nullable=False, comment='0=deliberate, 1=impulsive — inferred from this scenario'),
    sa.Column('evidence_attention_control', sa.Float(), nullable=False, comment='0=distracted, 1=focused — inferred from this scenario'),
    sa.Column('evidence_notification_fixation', sa.Float(), nullable=False, comment='0=ignores notifications, 1=fixated — inferred from distraction clicks'),
    sa.Column('evidence_urgency_susceptibility', sa.Float(), nullable=False, comment='0=ignores urgency, 1=highly susceptible — inferred from countdown/pressure behavior'),
    sa.Column('evidence_authority_compliance', sa.Float(), nullable=False, comment='0=resists authority, 1=complies — inferred from conflicting-authority scenario'),
    sa.Column('evidence_cognitive_overload', sa.Float(), nullable=False, comment='0=handles complexity, 1=overloaded — inferred from performance under complexity'),
    sa.Column('raw_telemetry', sa.Text(), nullable=True, comment='JSON blob of full interaction event stream for auditability and re-scoring'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_events_user_id'), 'calibration_events', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('tag', sa.Enum('IMPULSIVE', 'DISTRACTED', 'SAFE', 'GENERAL', name='lessontag'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personality_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('impulsiveness_score', sa.Float(), nullable=False, comment='0=deliberate, 1=highly impulsive'),
    sa.Column('attention_control_score', sa.Float(), nullable=False, comment='0=easily distracted, 1=focused'),
    sa.Column('emotional_reactivity_score', sa.Float(), nullable=False, comment='0=calm, 1=emotionally reactive'),
    sa.Column('authority_compliance_score', sa.Float(), nullable=False, comment='0=resists authority, 1=strongly complies'),
    sa.Column('cognitive_patience_score', sa.Float(), nullable=False, comment='0=impatient, 1=very patient'),
    sa.Column('risk_tolerance_score', sa.Float(), nullable=False, comment='0=risk averse, 1=risk seeking'),
    sa.Column('stress_resilience_score', sa.Float(), nullable=False, comment='0=stress-prone, 1=highly resilient'),
    sa.Column('multitasking_tendency_score', sa.Float(), nullable=False, comment='0=single-tasker, 1=habitual multitasker'),
    sa.Column('onboarding_profile_label', sa.String(length=50), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False, comment='1.0=perfect self-awareness, 0.0=strong mismatch'),
    sa.Column('self_awareness_score', sa.Float(), nullable=False, comment='How accurately user predicts their own behavior'),
    sa.Column('impulsiveness_mismatch', sa.Float(), nullable=False, comment='Delta: self-reported vs simulated impulsiveness'),
    sa.Column('attention_mismatch', sa.Float(), nullable=False, comment='Delta: self-reported vs simulated attention fragmentation'),
    sa.Column('emotional_stability_mismatch', sa.Float(), nullable=False, comment='Delta: self-reported calm vs simulated reactivity'),
    sa.Column('raw_answers', sa.Text(), nullable=True, comment='JSON array of {question_id, answer_value} submitted during onboarding'),
    sa.Column('calibration_completed', sa.Boolean(), nullable=False, comment='True once all behavioral calibration micro-simulations have been run'),
    sa.Column('calibration_confidence', sa.Float(), nullable=False, comment='0.0–1.0 confidence in behaviorally-inferred profile; increases with more scenario data'),
    sa.Column('prior_weight', sa.Float(), nullable=False, comment='Weight of self-report in blended profile (1.0=prior only, 0.3=behavioral dominant)'),
    sa.Column('behavioral_impulsiveness', sa.Float(), nullable=False, comment='Impulsiveness inferred from calibration scenario interaction timing'),
    sa.Column('behavioral_attention', sa.Float(), nullable=False, comment='Attention control inferred from distraction click patterns'),
    sa.Column('behavioral_notification_fixation', sa.Float(), nullable=False, comment='New dimension: how strongly user is drawn to notification stimuli'),
    sa.Column('behavioral_urgency_susceptibility', sa.Float(), nullable=False, comment='New dimension: susceptibility to urgency/countdown pressure'),
    sa.Column('behavioral_authority_compliance', sa.Float(), nullable=False, comment='Authority compliance inferred from conflicting-authority scenario'),
    sa.Column('behavioral_cognitive_overload', sa.Float(), nullable=False, comment='New dimension: how quickly cognitive load collapses under complexity'),
    sa.Column('overconfidence_index', sa.Float(), nullable=False, comment='Positive=user overestimates own control; Negative=underestimates. Range: -1.0 to 1.0'),
    sa.Column('mismatch_flags', sa.Text(), nullable=True, comment='JSON array of human-readable mismatch descriptions from Layer 3 analysis'),
    sa.Column('onboarding_telemetry', sa.Text(), nullable=True, comment='JSON blob of aggregated calibration scenario telemetry for re-scoring'),
    sa.Column('total_simulations_since_assessment', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personality_profiles_user_id'), 'personality_profiles', ['user_id'], unique=True)
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('distraction_type', sa.Enum('incoming_call', 'whatsapp_notification', 'gps_rerouting', 'email_alert', 'social_media', name='eventtype'), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False, comment='easy | medium | hard'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('instruction_text', sa.Text(), nullable=False, comment='Text shown to user about what the agent says'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('profile_type', sa.Enum('unknown', 'impulsive', 'overconfident', 'anxious', 'distractible', 'rule_following', name='profiletype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_reminders', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('weekly_progress', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('coaching_recommendations', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('assessment_reminders', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_notifications', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('difficulty', sa.String(length=50), server_default='Adaptive', nullable=False),
    sa.Column('intensity', sa.String(length=50), server_default='Standard', nullable=False),
    sa.Column('audio_guidance', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('behavioral_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('decision_type', sa.Enum('impulsive_unsafe', 'acceptable', 'delayed_hesitant', 'safe_ignore', 'risky', name='decisiontype'), nullable=False),
    sa.Column('pattern_flags', sa.Text(), nullable=True, comment='Comma-separated pattern tags (e.g., quick_reactor, frequent_distraction)'),
    sa.Column('is_risky', sa.Boolean(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_logs_session_id'), 'behavioral_logs', ['session_id'], unique=False)
    op.create_table('cognitive_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=False, comment='High-level behavioral interpretation paragraph'),
    sa.Column('cognitive_analysis', sa.Text(), nullable=False, comment='How the driver thinks under pressure — mechanistic interpretation'),
    sa.Column('emotional_trigger_breakdown', sa.Text(), nullable=False, comment='JSON: {trigger_type, susceptibility_pct, explanation}[]'),
    sa.Column('behavioral_timeline', sa.Text(), nullable=False, comment='JSON: [{event_num, scenario_type, decision, reaction_time, cognitive_state, interpretation}]'),
    sa.Column('attention_stability_analysis', sa.Text(), nullable=False, comment='Focus degradation pattern narrative + structured metrics'),
    sa.Column('risk_projection', sa.Text(), nullable=False, comment='Future behavioral risk prediction paragraph'),
    sa.Column('consistency_analysis', sa.Text(), nullable=False, comment='Self-reported profile vs actual simulation behavior comparison'),
    sa.Column('intervention_strategy', sa.Text(), nullable=False, comment='JSON: [{technique, rationale, priority}] — personalized intervention plan'),
    sa.Column('coaching_narrative', sa.Text(), nullable=False, comment='Human-like psychological coaching voice — 3-4 paragraphs'),
    sa.Column('recommended_simulations', sa.Text(), nullable=False, comment='JSON: [{type, difficulty, rationale, targets_weakness}]'),
    sa.Column('urgency_susceptibility_index', sa.Float(), nullable=False, comment='0.0–1.0: how strongly urgency cues drove unsafe decisions'),
    sa.Column('authority_pressure_sensitivity', sa.Float(), nullable=False, comment='0.0–1.0: compliance rate under authority-framed pressure'),
    sa.Column('cognitive_overload_score', sa.Float(), nullable=False, comment='0.0–1.0: failure rate under compound distraction load'),
    sa.Column('emotional_reactivity_index', sa.Float(), nullable=False, comment='0.0–1.0: emotional decision influence rate'),
    sa.Column('defensive_attention_stability', sa.Float(), nullable=False, comment='0.0–1.0: sustained attention without degradation'),
    sa.Column('reassurance_seeking_probability', sa.Float(), nullable=False, comment='0.0–1.0: tendency to check after ignoring a distraction'),
    sa.Column('session_score', sa.Float(), nullable=False),
    sa.Column('safe_decision_rate', sa.Float(), nullable=False),
    sa.Column('total_events_in_session', sa.Integer(), nullable=False),
    sa.Column('driver_profile_at_time', sa.String(length=50), nullable=False),
    sa.Column('personality_label_at_time', sa.String(length=50), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=False),
    sa.Column('generation_stage', sa.String(length=20), nullable=False, comment='complete | partial | fallback'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cognitive_reports_session_id'), 'cognitive_reports', ['session_id'], unique=False)
    op.create_index(op.f('ix_cognitive_reports_user_id'), 'cognitive_reports', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('incoming_call', 'whatsapp_notification', 'gps_rerouting', 'email_alert', 'social_media', name='eventtype'), nullable=False),
    sa.Column('user_response', sa.Enum('ignored', 'interacted', 'voice_command', 'no_response', name='userresponsetype'), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True, comment='Reaction time in seconds'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('bug', 'feature', 'ux', 'general', 'simulation', name='feedbacktype'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'archived', name='feedbackstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='feedbackpriority'), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('screen_size', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('distraction_type', sa.String(length=50), nullable=False, comment='incoming_call | whatsapp_notification | gps_rerouting | email_alert | social_media'),
    sa.Column('driver_profile_at_generation', sa.String(length=50), nullable=False, comment='The driver profile type when this was generated'),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('narrative_context', sa.Text(), nullable=False, comment='The immersive story context: time of day, emotional state, traffic, prior events'),
    sa.Column('passenger_pressure_text', sa.Text(), nullable=False, comment='What the AI passenger says to create social pressure'),
    sa.Column('urgency_escalation_level', sa.Integer(), nullable=False, comment='1=mild hint, 2=moderate urgency, 3=high pressure escalation'),
    sa.Column('emotional_pressure_type', sa.String(length=50), nullable=False, comment='authority | social_obligation | urgency | guilt | fomo | safety_concern'),
    sa.Column('target_weakness', sa.String(length=100), nullable=False, comment='The specific psychological weakness this scenario targets'),
    sa.Column('escalation_stage_1', sa.Text(), nullable=False, comment="Initial hint text: 'You got a message.'"),
    sa.Column('escalation_stage_2', sa.Text(), nullable=False, comment="Mid escalation: 'This might be important.'"),
    sa.Column('escalation_stage_3', sa.Text(), nullable=False, comment="Peak pressure: 'Why haven't you responded? This could be urgent!'"),
    sa.Column('response_choices', sa.Text(), nullable=False, comment='JSON array of 4 contextual choices generated by LLM'),
    sa.Column('ai_provider', sa.String(length=50), nullable=False),
    sa.Column('was_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_scenarios_session_id'), 'generated_scenarios', ['session_id'], unique=False)
    op.create_index(op.f('ix_generated_scenarios_user_id'), 'generated_scenarios', ['user_id'], unique=False)
    op.create_table('user_lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True, comment='The simulation session this lesson was generated from'),
    sa.Column('generated_reason', sa.String(length=500), nullable=True, comment='Specific reason this lesson was generated from the session'),
    sa.Column('recommended_focus', sa.String(length=300), nullable=True, comment='What the user should focus on during their next session'),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('lesson_category', sa.String(length=100), nullable=False, comment='Cognitive Control | Attention Regulation | Emotional Regulation | Defensive Decision | Recovery & Adaptation'),
    sa.Column('behavioral_diagnosis', sa.Text(), nullable=False, comment='Explain detected weakness'),
    sa.Column('psychological_interpretation', sa.Text(), nullable=False, comment='Why the behavior occurred cognitively/emotionally'),
    sa.Column('real_world_risk_impact', sa.Text(), nullable=False, comment='How this affects real driving behavior'),
    sa.Column('cognitive_coaching_narrative', sa.Text(), nullable=False, comment='Human-like adaptive coaching, replacing ai_coaching_advice'),
    sa.Column('scenario_replay_analysis', sa.Text(), nullable=False, comment='Break down important simulation moments'),
    sa.Column('behavioral_exercises', sa.Text(), nullable=False, comment='JSON array of interactive improvement drills'),
    sa.Column('mental_conditioning_techniques', sa.Text(), nullable=False, comment='JSON array of techniques like delayed-response conditioning'),
    sa.Column('attention_reinforcement_tasks', sa.Text(), nullable=False, comment='JSON array of practical training suggestions'),
    sa.Column('future_risk_projection', sa.Text(), nullable=False, comment='What happens if behavior continues'),
    sa.Column('personalized_improvement_strategy', sa.Text(), nullable=False, comment='Adaptive intervention roadmap'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment='Beginner | Intermediate | Advanced'),
    sa.Column('driver_type', sa.String(length=50), nullable=False, comment='Driver profile type when this lesson was generated'),
    sa.Column('reaction_time_target', sa.Float(), nullable=False, comment='Target avg reaction time in seconds'),
    sa.Column('distraction_tolerance_target', sa.Float(), nullable=False, comment='Target safe decision ratio 0.0-1.0'),
    sa.Column('ai_provider', sa.String(length=50), nullable=False, comment='Which LLM provider generated this lesson'),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False, comment='Number of times this lesson was reviewed/retaken'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_lessons_user_id'), 'user_lessons', ['user_id'], unique=False)
    op.create_table('feedback_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervention_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_event_id', sa.String(length=36), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('intervention_phase', sa.String(length=50), nullable=False),
    sa.Column('strategy_used', sa.String(length=100), nullable=False),
    sa.Column('dialogue_text', sa.String(length=500), nullable=True),
    sa.Column('prior_consecutive_mistakes', sa.Integer(), nullable=True),
    sa.Column('prior_reaction_time', sa.Float(), nullable=True),
    sa.Column('next_event_id', sa.String(length=36), nullable=True),
    sa.Column('resulting_decision', sa.String(length=50), nullable=True),
    sa.Column('resulting_reaction_time', sa.Float(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed data for initial scenarios
    op.execute("""
        INSERT INTO scenarios (id, name, description, distraction_type, difficulty_level, is_active, instruction_text)
        VALUES
            ('scenario-001', 'Incoming Phone Call',
             'Your phone rings while driving. A call from an unknown number flashes on screen.',
             'incoming_call', 'medium', true,
             'Your phone is ringing! What do you do?'),
            ('scenario-002', 'WhatsApp Notification',
             'A WhatsApp message notification buzzes. The preview shows an urgent message from a friend.',
             'whatsapp_notification', 'easy', true,
             'You just got a WhatsApp message. How do you respond?'),
            ('scenario-003', 'GPS Rerouting Alert',
             'Your GPS app is recalculating the route and shows a new turn coming in 200 meters.',
             'gps_rerouting', 'hard', true,
             'Your GPS is rerouting. Do you look at the screen while driving?')
        ON CONFLICT (id) DO NOTHING;
    """)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervention_logs')
    op.drop_table('feedback_notes')
    op.drop_table('feedback_attachments')
    op.drop_index(op.f('ix_user_lessons_user_id'), table_name='user_lessons')
    op.drop_table('user_lessons')
    op.drop_index(op.f('ix_generated_scenarios_user_id'), table_name='generated_scenarios')
    op.drop_index(op.f('ix_generated_scenarios_session_id'), table_name='generated_scenarios')
    op.drop_table('generated_scenarios')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_cognitive_reports_user_id'), table_name='cognitive_reports')
    op.drop_index(op.f('ix_cognitive_reports_session_id'), table_name='cognitive_reports')
    op.drop_table('cognitive_reports')
    op.drop_index(op.f('ix_behavioral_logs_session_id'), table_name='behavioral_logs')
    op.drop_table('behavioral_logs')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_personality_profiles_user_id'), table_name='personality_profiles')
    op.drop_table('personality_profiles')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_calibration_events_user_id'), table_name='calibration_events')
    op.drop_table('calibration_events')
    op.drop_index(op.f('ix_behavioral_states_user_id'), table_name='behavioral_states')
    op.drop_table('behavioral_states')
    op.drop_table('ai_feedback_insights_cache')
    op.drop_table('admin_platform_insights_cache')
    # ### end Alembic commands ###
