"""Add user_settings table

Revision ID: a284891cf269
Revises: 6a8d1bce503f
Create Date: 2026-05-28 05:14:01.087504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a284891cf269'
down_revision: Union[str, None] = '6a8d1bce503f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_reminders', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('weekly_progress', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('coaching_recommendations', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('assessment_reminders', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_notifications', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('difficulty', sa.String(length=50), server_default='Adaptive', nullable=False),
    sa.Column('intensity', sa.String(length=50), server_default='Standard', nullable=False),
    sa.Column('audio_guidance', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
