"""Sync user_lessons schema

Revision ID: acb98383fae0
Revises: a401d280e74f
Create Date: 2026-05-27 11:27:51.684905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb98383fae0'
down_revision: Union[str, None] = 'a401d280e74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lessons', sa.Column('lesson_category', sa.String(length=100), nullable=False, comment='Cognitive Control | Attention Regulation | Emotional Regulation | Defensive Decision | Recovery & Adaptation'))
    op.add_column('user_lessons', sa.Column('behavioral_diagnosis', sa.Text(), nullable=False, comment='Explain detected weakness'))
    op.add_column('user_lessons', sa.Column('psychological_interpretation', sa.Text(), nullable=False, comment='Why the behavior occurred cognitively/emotionally'))
    op.add_column('user_lessons', sa.Column('real_world_risk_impact', sa.Text(), nullable=False, comment='How this affects real driving behavior'))
    op.add_column('user_lessons', sa.Column('cognitive_coaching_narrative', sa.Text(), nullable=False, comment='Human-like adaptive coaching, replacing ai_coaching_advice'))
    op.add_column('user_lessons', sa.Column('scenario_replay_analysis', sa.Text(), nullable=False, comment='Break down important simulation moments'))
    op.add_column('user_lessons', sa.Column('behavioral_exercises', sa.Text(), nullable=False, comment='JSON array of interactive improvement drills'))
    op.add_column('user_lessons', sa.Column('mental_conditioning_techniques', sa.Text(), nullable=False, comment='JSON array of techniques like delayed-response conditioning'))
    op.add_column('user_lessons', sa.Column('attention_reinforcement_tasks', sa.Text(), nullable=False, comment='JSON array of practical training suggestions'))
    op.add_column('user_lessons', sa.Column('future_risk_projection', sa.Text(), nullable=False, comment='What happens if behavior continues'))
    op.add_column('user_lessons', sa.Column('personalized_improvement_strategy', sa.Text(), nullable=False, comment='Adaptive intervention roadmap'))
    op.drop_column('user_lessons', 'exercises')
    op.drop_column('user_lessons', 'improvement_goal')
    op.drop_column('user_lessons', 'ai_coaching_advice')
    op.drop_column('user_lessons', 'why_it_matters')
    op.drop_column('user_lessons', 'simulation_modes')
    op.drop_column('user_lessons', 'behavioral_target')
    op.drop_column('user_lessons', 'personalized_insight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lessons', sa.Column('personalized_insight', sa.TEXT(), autoincrement=False, nullable=False, comment="Personalized insight based on user's specific data"))
    op.add_column('user_lessons', sa.Column('behavioral_target', sa.VARCHAR(length=300), autoincrement=False, nullable=False, comment='The specific behavioral weakness this lesson addresses'))
    op.add_column('user_lessons', sa.Column('simulation_modes', sa.TEXT(), autoincrement=False, nullable=False, comment='JSON array of recommended simulation modes'))
    op.add_column('user_lessons', sa.Column('why_it_matters', sa.TEXT(), autoincrement=False, nullable=False, comment='Psychological + safety explanation'))
    op.add_column('user_lessons', sa.Column('ai_coaching_advice', sa.TEXT(), autoincrement=False, nullable=False, comment='2-4 sentence adaptive coaching generated by LLM'))
    op.add_column('user_lessons', sa.Column('improvement_goal', sa.VARCHAR(length=300), autoincrement=False, nullable=False, comment="Estimated improvement target, e.g. 'Reduce unsafe reactions by 15% in 5 sessions'"))
    op.add_column('user_lessons', sa.Column('exercises', sa.TEXT(), autoincrement=False, nullable=False, comment='JSON array of recommended exercise strings'))
    op.drop_column('user_lessons', 'personalized_improvement_strategy')
    op.drop_column('user_lessons', 'future_risk_projection')
    op.drop_column('user_lessons', 'attention_reinforcement_tasks')
    op.drop_column('user_lessons', 'mental_conditioning_techniques')
    op.drop_column('user_lessons', 'behavioral_exercises')
    op.drop_column('user_lessons', 'scenario_replay_analysis')
    op.drop_column('user_lessons', 'cognitive_coaching_narrative')
    op.drop_column('user_lessons', 'real_world_risk_impact')
    op.drop_column('user_lessons', 'psychological_interpretation')
    op.drop_column('user_lessons', 'behavioral_diagnosis')
    op.drop_column('user_lessons', 'lesson_category')
    # ### end Alembic commands ###
