"""Add session_id and generated_reason to user_lessons

Revision ID: f3b36928a611
Revises: 3c79afc2ecef
Create Date: 2026-05-18 11:09:53.770823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b36928a611'
down_revision: Union[str, None] = '3c79afc2ecef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lessons', sa.Column('session_id', sa.String(length=36), nullable=True, comment='The simulation session this lesson was generated from'))
    op.add_column('user_lessons', sa.Column('generated_reason', sa.String(length=500), nullable=True, comment='Specific reason this lesson was generated from the session'))
    op.add_column('user_lessons', sa.Column('recommended_focus', sa.String(length=300), nullable=True, comment='What the user should focus on during their next session'))
    op.create_foreign_key(None, 'user_lessons', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_lessons', type_='foreignkey')
    op.drop_column('user_lessons', 'recommended_focus')
    op.drop_column('user_lessons', 'generated_reason')
    op.drop_column('user_lessons', 'session_id')
    # ### end Alembic commands ###
