"""Add user_lessons table correctly

Revision ID: 3c79afc2ecef
Revises: 43b67b0df2ad
Create Date: 2026-05-18 10:53:27.955574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c79afc2ecef'
down_revision: Union[str, None] = '43b67b0df2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('behavioral_target', sa.String(length=300), nullable=False, comment='The specific behavioral weakness this lesson addresses'),
    sa.Column('why_it_matters', sa.Text(), nullable=False, comment='Psychological + safety explanation'),
    sa.Column('ai_coaching_advice', sa.Text(), nullable=False, comment='2-4 sentence adaptive coaching generated by LLM'),
    sa.Column('exercises', sa.Text(), nullable=False, comment='JSON array of recommended exercise strings'),
    sa.Column('personalized_insight', sa.Text(), nullable=False, comment="Personalized insight based on user's specific data"),
    sa.Column('improvement_goal', sa.String(length=300), nullable=False, comment="Estimated improvement target, e.g. 'Reduce unsafe reactions by 15% in 5 sessions'"),
    sa.Column('simulation_modes', sa.Text(), nullable=False, comment='JSON array of recommended simulation modes'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment='Beginner | Intermediate | Advanced'),
    sa.Column('driver_type', sa.String(length=50), nullable=False, comment='Driver profile type when this lesson was generated'),
    sa.Column('reaction_time_target', sa.Float(), nullable=False, comment='Target avg reaction time in seconds'),
    sa.Column('distraction_tolerance_target', sa.Float(), nullable=False, comment='Target safe decision ratio 0.0-1.0'),
    sa.Column('ai_provider', sa.String(length=50), nullable=False, comment='Which LLM provider generated this lesson'),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completion_score', sa.Float(), nullable=True, comment='Score achieved when completing the lesson (0-100)'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_lessons_user_id'), 'user_lessons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_lessons_user_id'), table_name='user_lessons')
    op.drop_table('user_lessons')
    # ### end Alembic commands ###
