"""Add admin platform insights cache

Revision ID: 3feefaa8861d
Revises: 88678503a779
Create Date: 2026-06-01 13:27:51.501715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3feefaa8861d'
down_revision: Union[str, None] = '88678503a779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_platform_insights_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('insights_text', sa.Text(), nullable=False),
    sa.Column('analyzed_users_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_sessions_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_platform_insights_cache')
    # ### end Alembic commands ###
