"""add_response_choices

Revision ID: 56cd66feb9c6
Revises: 1de207e2f5ee
Create Date: 2026-05-20 11:01:27.386289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cd66feb9c6'
down_revision: Union[str, None] = '1de207e2f5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_scenarios', sa.Column('response_choices', sa.Text(), nullable=False, comment='JSON array of 4 contextual choices generated by LLM'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_scenarios', 'response_choices')
    # ### end Alembic commands ###
