"""Add cognitive_reports table

Revision ID: 9ef1e45e1eca
Revises: 1a74ea8c0d51
Create Date: 2026-05-26 08:14:00.718097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef1e45e1eca'
down_revision: Union[str, None] = '1a74ea8c0d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
