"""baseline_schema

Revision ID: a9c3df28e166
Revises: 
Create Date: 2026-05-17 15:07:34.797208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c3df28e166'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavioral_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('safe_decisions', sa.Integer(), nullable=False),
    sa.Column('unsafe_decisions', sa.Integer(), nullable=False),
    sa.Column('impulsive_count', sa.Integer(), nullable=False),
    sa.Column('hesitant_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_mistakes', sa.Integer(), nullable=False),
    sa.Column('pressure_level', sa.Integer(), nullable=False),
    sa.Column('avg_reaction_time', sa.Float(), nullable=False),
    sa.Column('fastest_reaction', sa.Float(), nullable=False),
    sa.Column('slowest_reaction', sa.Float(), nullable=False),
    sa.Column('fail_scenario_counts', sa.String(length=512), nullable=False),
    sa.Column('dominant_fail_scenario', sa.String(length=64), nullable=False),
    sa.Column('pressure_yield_count', sa.Integer(), nullable=False),
    sa.Column('pressure_resist_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_states_user_id'), 'behavioral_states', ['user_id'], unique=True)
    op.create_table('intervention_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_event_id', sa.String(length=36), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('intervention_phase', sa.String(length=50), nullable=False),
    sa.Column('strategy_used', sa.String(length=100), nullable=False),
    sa.Column('dialogue_text', sa.String(length=500), nullable=True),
    sa.Column('prior_consecutive_mistakes', sa.Integer(), nullable=True),
    sa.Column('prior_reaction_time', sa.Float(), nullable=True),
    sa.Column('next_event_id', sa.String(length=36), nullable=True),
    sa.Column('resulting_decision', sa.String(length=50), nullable=True),
    sa.Column('resulting_reaction_time', sa.Float(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervention_logs')
    op.drop_index(op.f('ix_behavioral_states_user_id'), table_name='behavioral_states')
    op.drop_table('behavioral_states')
    # ### end Alembic commands ###
